name: "Chromatic"

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.15.3

      - name: Install dependencies
        # ⚠️ Pick one of these, matching the package manager for your project
        run: pnpm install

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        env:
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
